name: deploy

on:
  push:
    branches:
      - main  # or 'master' if that’s your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force --remote-name origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
