name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # 3️⃣ Install MkDocs + Material theme
      - run: pip install mkdocs mkdocs-material

      # 4️⃣ Deploy using built-in GITHUB_TOKEN
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
